name: Generate Monthly Updates

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 28 * *' # Run on the 28th of every month at midnight UTC

permissions:
  pull-requests: write
  contents: write

jobs:
  update-packages:
    if: github.repository_owner == 'unjs'
    name: Update Packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
      - run: corepack enable
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - run: pnpm jiti scripts/releases-article.ts

      - name: Commit
        run: |
          git config --local user.email $EMAIL
          git config --local user.name $USERNAME
          git checkout -b monthly-updates
          git add .
          git commit -m "content: create monthly updates"
          git push -f origin main
        env:
          EMAIL: ${{ secrets.EMAIL }}
          USERNAME: ${{ secrets.USERNAME }}

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pullRequests } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `${context.repo.owner}:monthly-updates`,
            })

            if (pullRequests.length === 0) {
              await github.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'content: create monthly updates',
                head: 'monthly-updates',
                base: 'main',
                body: 'This is an automated pull request to create monthly updates.',
              })
            }
